/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface InitGameRequest {
  boardJson: string
  randomSetup: boolean
}
export interface InitGameResponse {
  piecesJson: string
  turn: string
  phase: string
  setupStep: number
  turnCounter: number
  isNewTurn: boolean
  movesThisTurn: number
}
export declare function initGameStateNapi(req: InitGameRequest): InitGameResponse
export interface RandomizeRequest {
  boardJson: string
  piecesJson: string
  turn: string
  phase: string
  setupStep: number
  colorChosen: Record<string, string>
  turnCounter: number
  isNewTurn: boolean
  movesThisTurn: number
  lockedSequencePiece?: string
  heroeTakeCounter: number
  side: string
}
export interface RandomizeResponse {
  piecesJson: string
  turn: string
  phase: string
  setupStep: number
  turnCounter: number
  isNewTurn: boolean
  movesThisTurn: number
  lockedSequencePiece?: string
  heroeTakeCounter: number
}
export declare function randomizeSetupNapi(req: RandomizeRequest): RandomizeResponse
export interface MoveRequest {
  boardJson: string
  piecesJson: string
  pieceId: string
  turn: string
  phase: string
  setupStep: number
  colorChosen: Record<string, string>
  colorsEverChosen: Array<string>
  turnCounter: number
  isNewTurn: boolean
  movesThisTurn: number
  lockedSequencePiece?: string
  heroeTakeCounter: number
}
export interface MoveResponse {
  targets: Array<string>
  colorChosen: Record<string, string>
  colorsEverChosen: Array<string>
  mageUnlocked: boolean
  phase: string
  setupStep: number
  turn: string
  turnCounter: number
  isNewTurn: boolean
  movesThisTurn: number
  lockedSequencePiece?: string
  heroeTakeCounter: number
}
export declare function getLegalMovesNapi(req: MoveRequest): MoveResponse
export interface ApplyMoveRequest {
  boardJson: string
  piecesJson: string
  pieceId: string
  targetPoly: string
  turn: string
  phase: string
  setupStep: number
  colorChosen: Record<string, string>
  colorsEverChosen: Array<string>
  turnCounter: number
  isNewTurn: boolean
  movesThisTurn: number
  lockedSequencePiece?: string
  heroeTakeCounter: number
}
export interface SelectColorRequest {
  boardJson: string
  piecesJson: string
  color: string
  turn: string
  phase: string
  setupStep: number
  colorChosen: Record<string, string>
  colorsEverChosen: Array<string>
  turnCounter: number
  isNewTurn: boolean
  movesThisTurn: number
  lockedSequencePiece?: string
  heroeTakeCounter: number
}
export interface ApplyMoveResponse {
  piecesJson: string
  captured: Array<string>
  colorChosen: Record<string, string>
  colorsEverChosen: Array<string>
  mageUnlocked: boolean
  phase: string
  setupStep: number
  turn: string
  turnCounter: number
  isNewTurn: boolean
  movesThisTurn: number
  lockedSequencePiece?: string
  heroeTakeCounter: number
}
export interface EndTurnSetupRequest {
  boardJson: string
  piecesJson: string
  turn: string
  phase: string
  setupStep: number
  colorChosen: Record<string, string>
  colorsEverChosen: Array<string>
  turnCounter: number
  isNewTurn: boolean
  movesThisTurn: number
  lockedSequencePiece?: string
  heroeTakeCounter: number
}
export declare function endTurnSetupNapi(req: EndTurnSetupRequest): ApplyMoveResponse
export declare function applyMoveNapi(req: ApplyMoveRequest): ApplyMoveResponse
export declare function passTurnPlayingNapi(req: ApplyMoveRequest): ApplyMoveResponse
export declare function selectColorNapi(req: SelectColorRequest): ApplyMoveResponse
