#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_roles_dart.py
======================
Reads  backend/src/config/roles.json
Writes frontend/lib/utils/roles.dart

Run this script whenever roles.json changes:
    python generate_roles_dart.py

The pre-commit hook (.git/hooks/pre-commit) runs it automatically and
blocks commits if roles.dart is not up to date.
"""

import json
import os
import sys

# ── Paths (relative to this script's location) ───────────────────────────────
SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
ROLES_JSON  = os.path.join(SCRIPT_DIR, 'backend', 'src', 'config', 'roles.json')
ROLES_DART  = os.path.join(SCRIPT_DIR, 'frontend', 'lib', 'utils', 'roles.dart')


def dart_list(items: list) -> str:
    quoted = ', '.join(f'"{v}"' for v in items)
    return f'[{quoted}]'


def dart_map_int(d: dict) -> str:
    pairs = ', '.join(f'"{k}": {v}' for k, v in d.items())
    return '{ ' + pairs + ' }'


def generate(roles: dict) -> str:
    perms  = roles.get('permissions', {})
    limits = roles.get('limits', {})

    # ── permissions block ─────────────────────────────────────────────────────
    perm_lines = []
    for action, roles_list in perms.items():
        perm_lines.append(f'    "{action}": {dart_list(roles_list)},')
    perm_block = '\n'.join(perm_lines)

    # ── limits block ─────────────────────────────────────────────────────────
    # Compute column width for alignment
    max_key_len = max((len(k) for k in limits), default=0)
    limit_lines = []
    for name, role_vals in limits.items():
        padding = ' ' * (max_key_len - len(name))
        limit_lines.append(f'    "{name}":{padding} {dart_map_int(role_vals)},')
    limit_block = '\n'.join(limit_lines)

    return f'''\
// AUTO-GENERATED by generate_roles_dart.py — DO NOT EDIT MANUALLY.
// Source of truth: backend/src/config/roles.json
// To regenerate:  python generate_roles_dart.py  (from new_main/)
// A pre-commit hook enforces that this file stays in sync.

class Roles {{
  // ── Permissions ───────────────────────────────────────────────────────────
  static const Map<String, List<String>> permissions = {{
{perm_block}
  }};

  // ── Daily limits (-1 = unlimited) ────────────────────────────────────────
  static const Map<String, Map<String, int>> limits = {{
{limit_block}
  }};

  // ── Helpers ───────────────────────────────────────────────────────────────

  static bool canUser(String? role, String action) {{
    final r = role ?? 'guest';
    final allowed = permissions[action];
    if (allowed == null) return false;
    return allowed.contains(r);
  }}

  static int getLimit(String? role, String limitName) {{
    final r = role ?? 'guest';
    final typeLimits = limits[limitName];
    if (typeLimits == null) return 0;
    return typeLimits[r] ?? typeLimits['guest'] ?? 0;
  }}
}}
'''


def main():
    # Read JSON
    if not os.path.exists(ROLES_JSON):
        print(f'ERROR: {ROLES_JSON} not found.', file=sys.stderr)
        sys.exit(1)

    with open(ROLES_JSON, 'r', encoding='utf-8') as f:
        roles = json.load(f)

    dart_content = generate(roles)

    # Check whether the file actually changed (avoids spurious git diffs)
    if os.path.exists(ROLES_DART):
        with open(ROLES_DART, 'r', encoding='utf-8') as f:
            existing = f.read()
        if existing == dart_content:
            print('roles.dart is already up to date.')
            return

    with open(ROLES_DART, 'w', encoding='utf-8') as f:
        f.write(dart_content)

    print(f'roles.dart regenerated from roles.json.')


if __name__ == '__main__':
    main()
